### ISSUE TITLE
Compuscope: shutdown message is broken

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaqd-gage#32]
Traceback after a client requests shutdown:
```
Task exception was never retrieved
future: <Task finished coro=<IsDaemon._start_daemon() done, defined at [python path]\lib\site-packages\yaqd_core\_is_daemon.py:235> exception=UnboundLocalError("local variable 'daemon' referenced before assignment")>
Traceback (most recent call last):
  File "[python path]\lib\site-packages\yaqd_core\_is_daemon.py", line 254, in _start_daemon
    server(daemon), config.get("host", ""), config.get("port", None)
UnboundLocalError: local variable 'daemon' referenced before assignment
<6> INFO : 2023-07-14T14:33:13-0500 : daq : Connection lost from ('127.0.0.1', 51337) to daq
Task was destroyed but it is pending!
task: <Task pending coro=<IsDaemon.save_state() done, defined at [python path]\lib\site-packages\yaqd_core\_is_daemon.py:344> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000190B6B2FAF8>()]>>
Task exception was never retrieved
future: <Task finished coro=<HasMeasureTrigger._runner() done, defined at [python path]\lib\site-packages\yaqd_core\_has_measure_trigger.py:53> exception=AttributeError("'CompuScope' object has no attribute '_pg'")>
Traceback (most recent call last):
  File "[python path]\lib\site-packages\yaqd_core\_has_measure_trigger.py", line 56, in _runner
    self._measured = await self._measure()
  File "[python path]\lib\site-packages\yaqd_gage\_chopping.py", line 102, in _measure
    self._segment_count_limits = [1, self._pg.max_segment_count]
AttributeError: 'CompuScope' object has no attribute '_pg'
```

**Comment by ddkohler** [comment]
not sure about the log message we quoted above, but in general, compuscope daemon has trouble fully closing because we don't release the handle.  Using interface method `FreeSystem` within a context manager should fix this.  making sure the system can be freed should make clean shutdowns possible.
